#########################################################################################################################################################################
# Cell-type bias analysis: scRNA-seq annotation and SILAC proteostasis
#
# Purpose:
#   Annotate embryonic neocortex scRNA-seq data, quantify cell-type proportions,
#   and relate developmental cell-type changes to SILAC synthesis and degradation metrics.
#
# GitHub/reuse notes:
#   - Update the paths in "User settings" before running on another machine.
#   - The H5 files must retain the original 10x mm10 sparse-matrix structure.
#   - The SILAC input is generated by the preprocessing scripts as
#     Output/Objects/ProteomicsTimecourse_SILAC.rds.
#########################################################################################################################################################################


# ---- Logging and warning control ----
log_dir <- "./Output/Logs/"
dir.create(log_dir, recursive = TRUE, showWarnings = FALSE)

log_file <- file.path(
  log_dir,
  paste0("03d_Fig3_CellTypeBias_", format(Sys.time(), "%Y%m%d_%H%M%S"), ".log")
)

cat(
  "Cell-type bias analysis log\n",
  "Started: ", format(Sys.time()), "\n",
  "Working directory: ", getwd(), "\n\n",
  file = log_file,
  sep = ""
)

globalCallingHandlers(
  warning = function(w) {
    cat(
      "[WARNING] ", format(Sys.time()), "\n",
      conditionMessage(w), "\n\n",
      file = log_file,
      append = TRUE,
      sep = ""
    )
    invokeRestart("muffleWarning")
  },
  message = function(m) {
    cat(
      "[MESSAGE] ", format(Sys.time()), "\n",
      conditionMessage(m), "\n\n",
      file = log_file,
      append = TRUE,
      sep = ""
    )
    invokeRestart("muffleMessage")
  }
)

options(
  error = function() {
    cat(
      "[ERROR] ", format(Sys.time()), "\n",
      geterrmessage(), "\n\nTraceback:\n",
      file = log_file,
      append = TRUE,
      sep = ""
    )

    capture.output(traceback(2), file = log_file, append = TRUE)

    cat(
      "\nScript terminated: ", format(Sys.time()), "\n",
      file = log_file,
      append = TRUE,
      sep = ""
    )
  }
)

cat("Log file: ", normalizePath(log_file, mustWork = FALSE), "\n")


# ---- Loading packages ----
suppressPackageStartupMessages({
  library(dplyr)
  library(ggcorrplot)
  library(ggplot2)
  library(hdf5r)
  library(Matrix)
  library(rstatix)
  library(Seurat)
  library(tidyr)
})

set.seed(42)


# ---- User settings ----
path <- "./Output/"
data_path <- "./Data/SingleCell_DiBella2021/"

dir.create(path, recursive = TRUE, showWarnings = FALSE)

silac_file <- file.path(path, "Objects/ProteomicsTimecourse_SILAC.rds")

age_order <- c("E12.5", "E13.5", "E14.5", "E15.5", "E16.5")

h5_files <- c(
  E12.5 = file.path(data_path, "GSM4635073_E12_5_filtered_gene_bc_matrices_h5.h5"),
  E13.5 = file.path(data_path, "GSM4635074_E13_5_filtered_gene_bc_matrices_h5.h5"),
  E14.5 = file.path(data_path, "GSM4635075_E14_5_filtered_gene_bc_matrices_h5.h5"),
  E15.5 = file.path(data_path, "GSM4635076_E15_5_S1_filtered_gene_bc_matrices_h5.h5"),
  E16.5 = file.path(data_path, "GSM4635077_E16_filtered_gene_bc_matrices_h5.h5")
)

celltype_colors <- c(
  Radial_Glia = "#4292C6",
  Intermediate_Prog = "#84E7DF",
  Excit_Neuron_early = "#FD8D3C",
  Excit_Neuron_late = "#D94801",
  Inhib_Neuron = "#D97B01",
  Cajal_Retzius = "#BE6BFD",
  Endothelial = "#FD6BC3",
  Microglia = "#F226A0"
)

# Marker sources: Loo et al. 2019; Telley et al. 2019;
# Di Bella et al. 2021; Molyneaux et al. 2007.
markers <- list(
  Radial_Glia = c("Pax6", "Sox2", "Nes", "Vim", "Slc1a3", "Fabp7", "Hes1", "Hes5", "Aldoc"),
  Intermediate_Prog = c("Eomes", "Insm1", "Neurog2", "Btg2", "Gadd45g", "Sstr2"),
  Excit_Neuron_early = c("Tbr1", "Neurod6", "Bcl11b", "Fezf2", "Sox5"),
  Excit_Neuron_late = c("Satb2", "Cux1", "Cux2", "Rorb", "Pou3f2", "Pou3f3"),
  Inhib_Neuron = c("Gad1", "Gad2", "Dlx1", "Dlx2", "Lhx6", "Arx"),
  Cajal_Retzius = c("Reln", "Lhx5", "Trp73", "Calb2"),
  Endothelial = c("Pecam1", "Cldn5", "Esam", "Kdr"),
  Microglia = c("Cx3cr1", "Aif1", "Tmem119", "P2ry12", "Csf1r")
)

marker_celltypes <- c(
  "Radial_Glia",
  "Intermediate_Prog",
  "Excit_Neuron_early",
  "Excit_Neuron_late",
  "Inhib_Neuron"
)

missing_inputs <- c(h5_files, silac_file)[!file.exists(c(h5_files, silac_file))]
if (length(missing_inputs) > 0) {
  stop(
    "Missing input files:\n",
    paste0("  - ", missing_inputs, collapse = "\n"),
    "\nUpdate the paths in the User settings section."
  )
}


# ---- Load and quality-control scRNA-seq data ----
load_h5_seurat <- function(file, age) {
  h5 <- H5File$new(file, mode = "r")
  on.exit(h5$close_all(), add = TRUE)

  counts <- sparseMatrix(
    i = h5[["mm10/indices"]][] + 1L,
    p = h5[["mm10/indptr"]][],
    x = as.numeric(h5[["mm10/data"]][]),
    dims = h5[["mm10/shape"]][],
    dimnames = list(
      make.unique(h5[["mm10/gene_names"]][]),
      paste0(age, "_", h5[["mm10/barcodes"]][])
    )
  )

  object <- CreateSeuratObject(
    counts = counts,
    project = age,
    min.cells = 3,
    min.features = 200
  )
  object$age <- age
  object
}

seurat_list <- lapply(names(h5_files), function(age) {
  object <- load_h5_seurat(h5_files[[age]], age)
  object[["pct_mt"]] <- PercentageFeatureSet(object, pattern = "^mt-")
  subset(object, subset = nFeature_RNA < 6000 & pct_mt < 20)
})
names(seurat_list) <- names(h5_files)

qc_table <- bind_rows(lapply(names(seurat_list), function(age) {
  data.frame(age = age, cells_after_qc = ncol(seurat_list[[age]]))
}))



# ---- Integrate, cluster and annotate scRNA-seq data ----
combined <- merge(
  x = seurat_list[[1]],
  y = seurat_list[-1],
  add.cell.ids = names(seurat_list)
)
combined$age <- factor(combined$age, levels = age_order)

combined <- NormalizeData(combined, verbose = FALSE)
combined <- FindVariableFeatures(combined, nfeatures = 3000, verbose = FALSE)
combined <- ScaleData(combined, verbose = FALSE)
combined <- RunPCA(combined, npcs = 50, verbose = FALSE)
combined <- harmony::RunHarmony(
  combined,
  group.by.vars = "age",
  reduction.use = "pca",
  verbose = FALSE
)
combined <- FindNeighbors(combined, reduction = "harmony", dims = 1:30, verbose = FALSE)
combined <- FindClusters(combined, resolution = 0.5, verbose = FALSE)
combined <- RunUMAP(combined, reduction = "harmony", dims = 1:30, verbose = FALSE)
combined <- JoinLayers(combined)

for (celltype in names(markers)) {
  available_markers <- intersect(markers[[celltype]], rownames(combined))

  if (length(available_markers) >= 2) {
    combined <- AddModuleScore(
      combined,
      features = list(available_markers),
      name = celltype,
      ctrl = 50,
      verbose = FALSE
    )
    combined[[celltype]] <- combined[[paste0(celltype, "1")]]
    combined[[paste0(celltype, "1")]] <- NULL
  }
}

score_columns <- intersect(names(markers), colnames(combined@meta.data))
if (length(score_columns) == 0) {
  stop("No marker module scores were generated. Check marker names and gene identifiers.")
}

score_matrix <- as.matrix(combined@meta.data[, score_columns, drop = FALSE])
combined$cell_type <- score_columns[max.col(score_matrix, ties.method = "first")]
combined$cell_type[apply(score_matrix, 1, max) < 0] <- "Unknown"
combined$cell_type <- factor(combined$cell_type, levels = c(names(markers), "Unknown"))

saveRDS(combined, file.path(path, "Objects/Fig3_CellTypeBias_Seurat.rds"))

celltype_counts <- as.data.frame(table(combined$age, combined$cell_type))
colnames(celltype_counts) <- c("age", "cell_type", "cells")


# ---- Cell-type proportions ----
prop_df <- combined@meta.data %>%
  count(age, cell_type, name = "n") %>%
  group_by(age) %>%
  mutate(proportion = n / sum(n)) %>%
  ungroup() %>%
  filter(cell_type != "Unknown") %>%
  mutate(
    age = factor(age, levels = age_order),
    cell_type = factor(cell_type, levels = names(markers))
  )



# ---- Load and prepare SILAC data ----
silac <- readRDS(silac_file) %>%
  pivot_longer(
    cols = any_of(c(
      "ratios_HL", "ratios_HT", "ratios_LT", "riBAQ_H", "riBAQ_L",
      "iBAQ_H", "iBAQ_L", "LFQ_L", "LFQ_H", "LFQ_T", "H", "L", "t12"
    )),
    names_to = "Experiment",
    values_to = "Value"
  ) %>%
  mutate(Value = replace(Value, is.infinite(Value) | is.nan(Value), NA_real_)) %>%
  filter(
    !is.na(Value),
    Value > 0,
    Embryonic_Age %in% age_order,
    Incubation_Time == "4h"
  )

get_age_median <- function(experiment) {
  silac %>%
    filter(Experiment == experiment) %>%
    group_by(Embryonic_Age) %>%
    summarise(median_val = median(log2(Value), na.rm = TRUE), .groups = "drop") %>%
    mutate(Embryonic_Age = factor(Embryonic_Age, levels = age_order))
}

get_protein_age <- function(experiment) {
  silac %>%
    filter(Experiment == experiment) %>%
    group_by(genes, Embryonic_Age) %>%
    summarise(value = median(log2(Value), na.rm = TRUE), .groups = "drop") %>%
    mutate(Embryonic_Age = factor(Embryonic_Age, levels = age_order))
}

available_experiments <- unique(silac$Experiment)
trajectory_experiments <- intersect(
  c("ratios_HL", "ratios_HT", "t12", "riBAQ_H", "iBAQ_H", "LFQ_H", "H", "LFQ_T"),
  available_experiments
)

metric_labels <- c(
  ratios_HL = "log2 H/L",
  ratios_HT = "log2 H/T",
  t12 = "log2 half-life",
  riBAQ_H = "log2 riBAQ heavy",
  iBAQ_H = "log2 iBAQ heavy",
  LFQ_H = "log2 LFQ heavy",
  H = "log2 raw heavy",
  LFQ_T = "log2 LFQ total"
)

marker_proteins <- bind_rows(lapply(marker_celltypes, function(celltype) {
  data.frame(
    genes = markers[[celltype]],
    cell_type = celltype,
    stringsAsFactors = FALSE
  )
}))


# ---- Extended Data Figure 3a ----
# Cell-type proportions across development 
p <- ggplot(prop_df, aes(x = age, y = proportion, fill = cell_type)) +
  geom_col(width = 0.75, colour = "white", linewidth = 0.2) +
  scale_fill_manual(
    values = celltype_colors,
    name = "Cell type",
    labels = function(x) gsub("_", " ", x)
  ) +
  scale_y_continuous(labels = scales::percent_format(), expand = c(0, 0)) +
  labs(x = "Embryonic age", y = "Proportion of cells") +
  theme_classic(base_size = 11) +
  theme(
    legend.position = "right",
    axis.text.x = element_text(angle = 30, hjust = 1)
  )

ggsave(
  file.path(path, "Figures/ExtFig3a_SingleCell_DiBella2021_CellTypeProportions_Barplot.pdf"),
  p,
  width = 7,
  height = 5
)


# ---- Figure 3c ----
# SILAC trajectories of cell-type marker proteins
trajectory_data <- bind_rows(lapply(trajectory_experiments, function(experiment) {
  get_protein_age(experiment) %>%
    inner_join(marker_proteins, by = "genes") %>%
    mutate(
      Experiment = experiment,
      metric = unname(metric_labels[experiment]),
      cell_type = factor(cell_type, levels = names(markers))
    )
}))

trajectory_summary <- trajectory_data %>%
  group_by(metric, cell_type, Embryonic_Age) %>%
  summarise(
    mean_value = mean(value, na.rm = TRUE),
    se_value = sd(value, na.rm = TRUE) / sqrt(sum(!is.na(value))),
    .groups = "drop"
  )

p <- ggplot(
  trajectory_summary,
  aes(x = Embryonic_Age, y = mean_value, colour = cell_type, group = cell_type)
) +
  geom_ribbon(
    aes(
      ymin = mean_value - se_value,
      ymax = mean_value + se_value,
      fill = cell_type
    ),
    alpha = 0.12,
    colour = NA
  ) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 2) +
  facet_wrap(~metric, scales = "free_y", ncol = 3) +
  scale_colour_manual(
    values = celltype_colors,
    name = "Cell type",
    labels = function(x) gsub("_", " ", x)
  ) +
  scale_fill_manual(values = celltype_colors, guide = "none") +
  labs(x = "Embryonic age", y = "Mean log2 value ± SE") +
  theme_classic(base_size = 11) +
  theme(
    legend.position = "right",
    strip.text = element_text(face = "bold"),
    axis.text.x = element_text(angle = 30, hjust = 1)
  )

ggsave(
  file.path(path, "Figures/Fig3c_CellTypeMarker_SILAC_Trajectories.pdf"),
  p,
  width = 13,
  height = 8
)


# ---- Extended Data Figure 3b ----
# Correlation between cell-type proportions and SILAC metrics
correlation_experiments <- intersect(c("ratios_HL", "ratios_HT"), available_experiments)

prop_wide <- prop_df %>%
  select(age, cell_type, proportion) %>%
  pivot_wider(names_from = cell_type, values_from = proportion) %>%
  mutate(age = as.character(age))

silac_wide <- bind_rows(lapply(correlation_experiments, function(experiment) {
  get_age_median(experiment) %>%
    mutate(metric = unname(metric_labels[experiment]))
})) %>%
  mutate(Embryonic_Age = as.character(Embryonic_Age)) %>%
  pivot_wider(names_from = metric, values_from = median_val)

combined_wide <- left_join(
  prop_wide,
  silac_wide,
  by = c("age" = "Embryonic_Age")
)

celltype_variables <- intersect(names(markers), colnames(combined_wide))
metric_variables <- intersect(unname(metric_labels[correlation_experiments]), colnames(combined_wide))

correlation_matrix <- matrix(
  NA_real_,
  nrow = length(celltype_variables),
  ncol = length(metric_variables),
  dimnames = list(celltype_variables, metric_variables)
)
pvalue_matrix <- correlation_matrix

for (celltype in celltype_variables) {
  for (metric in metric_variables) {
    correlation_data <- combined_wide %>%
      select(all_of(c(celltype, metric))) %>%
      drop_na()

    if (nrow(correlation_data) >= 4) {
      test <- cor.test(
        correlation_data[[celltype]],
        correlation_data[[metric]],
        method = "spearman",
        exact = FALSE
      )
      correlation_matrix[celltype, metric] <- unname(test$estimate)
      pvalue_matrix[celltype, metric] <- test$p.value
    }
  }
}

rownames(correlation_matrix) <- gsub("_", " ", rownames(correlation_matrix))
rownames(pvalue_matrix) <- gsub("_", " ", rownames(pvalue_matrix))

p <- ggcorrplot(
  correlation_matrix,
  p.mat = pvalue_matrix,
  sig.level = 0.05,
  insig = "pch",
  pch = 4,
  pch.cex = 3,
  method = "square",
  lab = TRUE,
  lab_size = 3.5,
  colors = c("#2166AC", "white", "#D6604D"),
  legend.title = "rho",
  ggtheme = theme_classic(base_size = 11)
) +
  labs(
    x = NULL,
    y = NULL,
    subtitle = "X: p > 0.05; n = 5 embryonic ages"
  ) +
  theme(
    axis.text.x = element_text(angle = 35, hjust = 1, size = 10),
    axis.text.y = element_text(size = 10)
  )

ggsave(
  file.path(path, "Figures/ExtFig3b_CellTypeProportion_SILAC_Correlation.pdf"),
  p,
  width = 8,
  height = 7
)


cat(
  "\nScript completed successfully: ",
  format(Sys.time()),
  "\n",
  file = log_file,
  append = TRUE,
  sep = ""
)


#########################################################################################################################################################################
# END OF SCRIPT
#########################################################################################################################################################################